name: CI - main

on:
  push:
    tags: [ '*' ]


jobs:
  build:
    uses: CESI-Eats/Template_CI/.github/workflows/node-docker.yaml@master
    with:
      version: ${{ github.ref_name }}

  deploy: 
    needs: build
    uses: CESI-Eats/Identity_DEPLOY/.github/workflows/deploy.yaml@main